name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cicd:
    uses: ./.github/workflows/reusable-cicd.yml
    with:
      # Version configuration
      major-version: '8'
      minor-version: '0'
      
      # .NET configuration
      dotnet-version: '8.0.x'
      nuget-projects: 'SW.Surl.Sdk/SW.Surl.Sdk.csproj'
      run-tests: 'false'
      
      # Docker configuration
      dockerfile-path: './Dockerfile'
      docker-context: '.'
      
      # Helm configuration
      chart-name: 'surl'
      chart-path: './chart'
      
      # Deployment configuration
      deploy-to-development: true
      development-namespace: 'playground'
      
      # Registry configuration
      container-registry: 'ghcr.io'
      
      # Helm deployment values
      helm-set-values: 'ingress.enabled=true,replicas=1,ingress.hosts={surl.sf9.io},environment="Staging",db="$(dbcs)",ingress.path="/api",ingress.tls[0].secretName="surl-tls",ingress.annotations."cert-manager\.io/cluster-issuer"="letsencrypt-nginx"'
      
    secrets:
      # NuGet secrets
      nuget-api-key: ${{ secrets.SWNUGETKEY }}
      nuget-source: 'https://api.nuget.org/v3/index.json'
      
      # Container registry (using GitHub packages)
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      
      # Kubernetes
      kubeconfig: ${{ secrets.S9Dev_KUBECONFIG }}
      
      # GitHub token for tagging
      github-token: ${{ secrets.S9_GITHUB_TOKEN }}
