name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cicd:
    uses: simplify9/.github/.github/workflows/sw-cicd.yml@main
    secrets: inherit
    with:
      # Version configuration
      major-version: '8'
      minor-version: '0'
      
      # .NET configuration
      dotnet-version: '8.0.x'
      nuget-projects: 'SW.Surl.Sdk/SW.Surl.Sdk.csproj'
      run-tests: 'false'
      
      # Docker configuration
      dockerfile-path: './Dockerfile'
      docker-context: '.'
      
      # Helm configuration
      chart-name: 'surl'
      chart-path: './chart'
      
      # Deployment configuration
      deploy-to-development: true
      development-namespace: 'playground'
      
      # Registry configuration
      container-registry: 'ghcr.io'

      # Helm deployment values  
      helm-set-values: 'ingress.enabled=true,replicas=1,ingress.hosts={surl.sf9.io},environment="Staging",ingress.path="/api",ingress.tls[0].secretName="surl-tls"'

      # Map GitHub secrets to Helm values
      helm-secret-mappings: 'db:DBCS_ESCAPED' 


