name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cicd:
    uses: simplify9/.github/.github/workflows/sw-cicd.yml@main
    with:
      # Version configuration
      major-version: '8'
      minor-version: '0'
      
      # .NET configuration
      dotnet-version: '8.0.x'
      nuget-projects: 'SW.Surl.Sdk/SW.Surl.Sdk.csproj'
      run-tests: 'false'
      
      # Docker configuration
      dockerfile-path: './Dockerfile'
      docker-context: '.'
      
      # Helm configuration
      chart-name: 'surl'
      chart-path: './chart'
      
      # Deployment configuration
      deploy-to-development: true
      development-namespace: 'playground'
      
      # Registry configuration
      container-registry: 'ghcr.io'

      # Helm deployment values using variable reference  
      helm-set-values: |
        ingress.enabled=true,replicas=1,ingress.hosts={surl.sf9.io},environment="Staging",ingress.path="/api",ingress.tls[0].secretName="surl-tls",db="${nuget-source}"
    secrets:
      # Built-in workflow secrets (explicit mapping for org secrets)
      nuget-api-key: ${{ secrets.SWNUGETKEY }}
      kubeconfig: ${{ secrets.S9Dev_KUBECONFIG }}
      github-token: ${{ secrets.S9_GITHUB_TOKEN }}
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      
      # Repurpose nuget-source to pass database connection
      nuget-source: ${{ secrets.DBCS_DUMMY }} 


